inherit_from: "../.rubocop-common.yml"

AllCops:
  Exclude:
    - "test/rubocop-cases/**/*"
    - "core-docs/**/*"
Layout/LineLength:
  Exclude:
    - "*.gemspec"
Metrics/AbcSize:
  Exclude:
    - "builtins/**/*"
Metrics/BlockLength:
  Exclude:
    - "lib/toys/templates/*"
    - "test/**/*"
    - "builtins/**/*"
    - "*.gemspec"
    - ".toys.rb"
Metrics/BlockNesting:
  Exclude:
    - "lib/toys/templates/*"
    - "test/**/*"
Metrics/MethodLength:
  Exclude:
    - "builtins/**/*"
Naming/FileName:
  Exclude:
    - "builtins/**/*"
Style/BlockDelimiters:
  Exclude:
    - "test/**/*"
Style/Documentation:
  Exclude:
    - "test/**/*"
    - ".toys.rb"
Style/DocumentationMethod:
  Exclude:
    - ".toys.rb"
    - "builtins/**/*"
    - "test/**/*"
Style/MixinGrouping:
  Exclude:
    - ".toys.rb"
