AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "test/rubocop-cases/**/*"

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Max: 100
  Exclude:
    - "*.gemspec"
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - "builtins/**/*"
  Max: 25
Metrics/BlockLength:
  Exclude:
    - "lib/toys/templates/*"
    - "test/**/*"
    - "builtins/**/*"
    - "*.gemspec"
Metrics/BlockNesting:
  Exclude:
    - "lib/toys/templates/*"
    - "test/**/*"
Metrics/ClassLength:
  Max: 250
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Exclude:
    - "builtins/**/*"
  Max: 20
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Style/BlockDelimiters:
  Exclude:
    - "test/**/*"
Style/Documentation:
  Exclude:
    - "test/**/*"
Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - ".toys.rb"
    - "builtins/**/*"
    - "test/**/*"
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/WordArray:
  EnforcedStyle: brackets
