# frozen_string_literal: true

source "https://rubygems.org"

gemspec
gem "toys-core", path: "../toys-core"

gem "did_you_mean", "~> 1.0"
gem "highline", "~> 2.0"
gem "minitest", "~> 5.14"
gem "minitest-focus", "~> 1.1"
gem "minitest-rg", "~> 5.2"
gem "rake", "~> 13.0"
gem "rdoc", (::RUBY_VERSION < "2.4" ? "~> 6.1.2" : "~> 6.2.1")
gem "redcarpet", "~> 3.5" unless ::RUBY_PLATFORM == "java"
gem "rspec", "~> 3.9"
gem "rubocop", "~> 0.81.0"
gem "yard", "~> 0.9.25"
