# frozen_string_literal: true

source "https://rubygems.org"

gemspec
gem "toys-core", path: "../toys-core"

# The bundler in Ruby < 3.1 triggers a deprecation warning in did_you_mean 1.6
# resulting in test failures due to the unexpected output.
did_you_mean_versions = ::RUBY_VERSION < "3.1" ? ["~> 1.0", "< 1.6"] : ["~> 1.6"]
gem "did_you_mean", *did_you_mean_versions
gem "highline", "~> 2.0"
gem "minitest", "~> 5.14"
gem "minitest-focus", "~> 1.1"
gem "minitest-rg", "~> 5.2"
gem "rake", "~> 13.0"
gem "rdoc", "~> 6.3.3"
gem "redcarpet", "~> 3.5" unless ::RUBY_PLATFORM == "java"
gem "rspec", "~> 3.9"
gem "rubocop", "~> 1.12.1"
gem "yard", "~> 0.9.25"
