inherit_from: ".rubocop-common.yml"

AllCops:
  Include:
    - ".toys/**/*.rb"
    - ".toys/**/.toys.rb"
    - ".toys/**/.lib/**/*.rb"
    - "common-tools/**/.toys.rb"
  Exclude:
    - "toys/**/*"
    - "toys-core/**/*"
    - ".toys/release/**/*.rb" # TEMP
    - ".toys/release/.lib/*.rb" # TEMP
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 15
Naming/FileName:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 15
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
