inherit_from: ".rubocop-common.yml"

AllCops:
  Include:
    - ".toys/**/*.rb"
    - ".toys/**/.toys.rb"
    - ".toys/**/.lib/**/*.rb"
    - "common-tools/**/*.rb"
    - "common-tools/**/.toys.rb"
    - "common-tools/**/.lib/*.rb"
  Exclude:
    - "toys/**/*"
    - "toys-core/**/*"
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Naming/FileName:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 20
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
