AllCops:
  TargetRubyVersion: 2.3

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Max: 100
  Exclude:
    - "*.gemspec"
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
Metrics/BlockNesting:
  Exclude:
    - "test/**/*"
Metrics/ClassLength:
  Max: 500
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 25
Metrics/ModuleLength:
  Max: 500
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 10
Naming/FileName:
  Exclude:
    - "test/lookup-cases/**/*"
    - "lib/toys-core.rb"
    - "examples/**/*"
Style/BlockDelimiters:
  Exclude:
    - "test/**/*"
Style/BracesAroundHashParameters:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/Copyright:
  Enabled: true
  Exclude:
    - "test/lookup-cases/**/*"
    - "examples/**/*"
  Notice: 'Copyright \d{4} Daniel Azuma'
Style/Documentation:
  Exclude:
    - "test/**/*"
Style/DocumentationMethod:
  Enabled: true
  Exclude:
    - ".toys.rb"
    - "examples/**/*"
    - "test/**/*"
Style/GlobalVars:
  Exclude:
    - "test/lookup-cases/preloads/**/*.rb"
    - "test/test_loader.rb"
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
