inherit_from: "../.rubocop-common.yml"

AllCops:
  Exclude:
    - "test/gems-cases/bundle-with-vendored-path/vendor/**/*"
Layout/EmptyLinesAroundAttributeAccessor:
  Exclude:
    - "test/**/*.rb"
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/**/*.rb"
Layout/LineLength:
  Exclude:
    - "*.gemspec"
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"
Metrics/BlockNesting:
  Exclude:
    - "test/**/*"
Naming/FileName:
  Exclude:
    - "test/lookup-cases/**/*"
    - "lib/toys-core.rb"
    - "examples/**/*"
Naming/MethodParameterName:
  Exclude:
    - "lib/toys/dsl/tool.rb"
Style/BlockDelimiters:
  Exclude:
    - "test/**/*"
Style/Documentation:
  Exclude:
    - "test/**/*"
Style/DocumentationMethod:
  Exclude:
    - ".toys.rb"
    - "examples/**/*"
    - "test/**/*"
Style/GlobalVars:
  Exclude:
    - "test/lookup-cases/preloads/**/*.rb"
    - "test/test_loader.rb"
Style/NumericLiterals:
  Exclude:
    - "lib/toys/compat.rb"
