# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "did_you_mean", "~> 1.0"
gem "highline", "~> 2.0"
gem "minitest", "~> 5.14"
gem "minitest-focus", "~> 1.1"
gem "minitest-rg", "~> 5.2"
gem "rdoc", "~> 6.2.1"
gem "redcarpet", "~> 3.5" unless ::RUBY_PLATFORM == "java"
gem "rubocop", "~> 1.12.0"
gem "yard", "~> 0.9.25"
