# frozen_string_literal: true

source "https://rubygems.org"

gemspec

# The bundler in Ruby < 3.1 triggers a deprecation warning in did_you_mean 1.6
# resulting in test failures due to the unexpected output.
did_you_mean_versions = ::RUBY_VERSION < "3.1" ? ["~> 1.0", "< 1.6"] : ["~> 1.6"]
gem "did_you_mean", *did_you_mean_versions
gem "highline", "~> 2.0"
# Minitest 5.16 requires Ruby 2.6 or later. Allow 5.15+ for now.
gem "minitest", "~> 5.15"
gem "minitest-focus", "~> 1.3"
gem "minitest-rg", "~> 5.2"
# RDoc 6.4 requires Ruby 2.5 or later. Furthermore, to run on 2.5, it requires
# an update to rubygems. Thus, we'll pin to 6.3 for now.
gem "rdoc", "~> 6.3.3"
gem "redcarpet", "~> 3.5" unless ::RUBY_PLATFORM == "java"
gem "rubocop", "~> 1.12.1"
gem "yard", "~> 0.9.28"
