# frozen_string_literal: true

source "https://rubygems.org"

gem "minitest", ">= 5.26", "< 7"
gem "rack", ">= 3"
gem "toys-core", path: "../../../../../../../../toys-core"
gem "toys", path: "../../../../../../.."
