inherit_from: "../.rubocop-common.yml"

AllCops:
  Include:
    - "Gemfile"
    - "**/*.rb"
    - "**/.lib/**/*.rb"
    - "**/.test/**/*.rb"
    - "**/.toys/*.rb"
    - "**/.toys/.toys.rb"
  Exclude:
    - "**/.data/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Exclude:
    - "*.gemspec"

Metrics/BlockLength:
  Exclude:
    - "toys/.test/**/*"
    - "toys/*"
    - "*.gemspec"
Metrics/BlockNesting:
  Exclude:
    - "toys/.test/**/*"

Naming/FileName:
  Exclude:
    - "lib/toys-release.rb"
    - "toys/*"
    - "toys/.toys.rb"

Security/YAMLLoad:
  Exclude:
    - "toys/.test/**/*"
    - "toys/.lib/toys/release/repo_settings.rb"

Style/Documentation:
  Exclude:
    - "toys/.test/*.rb"
Style/DocumentationMethod:
  Exclude:
    - "toys/.test/*.rb"
    - "toys/*"
    - "toys/.toys.rb"
    - ".toys/.toys.rb"
